# Introduction

The data comes from the simulation presented at Kaggle's 'Transactions Fraud Detection Dataset'.

In [2]:
import pandas as pd
import sqlite3

df_path='C:/Users/u0135988/OneDrive - KU Leuven/Research/Quant/Methods_Quant_Fin/Example - Fraud Detection - Kaggle/fraudTest.csv'
db_path='C:/Users/u0135988/OneDrive - KU Leuven/Research/Quant/Methods_Quant_Fin/Example - Fraud Detection - Kaggle/fraud.db'


#Read the csv file called df for simplicity
df = pd.read_csv(df_path)

#Create a SQLite database
conn = sqlite3.connect(db_path) 
cursor = conn.cursor()

#Upload data to the SQLite database
table_name = 'fraud_data'
#df.to_sql is useful to write an existing data frame (here df) to sql
df.to_sql(table_name, conn, if_exists='replace', index=True) #index is to write df's idex as column

#Run queries on the database
query = f"SELECT * FROM {table_name} LIMIT 20;"  
#This pd function allows to execute a query and save outcome 
result = pd.read_sql_query(query, conn)
print(result)

# Close the connection
conn.close()

    index  Unnamed: 0 trans_date_trans_time               cc_num  \
0       0           0   2020-06-21 12:14:25     2291163933867244
1       1           1   2020-06-21 12:14:33     3573030041201292
2       2           2   2020-06-21 12:14:53     3598215285024754
3       3           3   2020-06-21 12:15:15     3591919803438423
4       4           4   2020-06-21 12:15:17     3526826139003047
5       5           5   2020-06-21 12:15:37       30407675418785
6       6           6   2020-06-21 12:15:44      213180742685905
7       7           7   2020-06-21 12:15:50     3589289942931264
8       8           8   2020-06-21 12:16:10     3596357274378601
9       9           9   2020-06-21 12:16:11     3546897637165774
10     10          10   2020-06-21 12:16:20     2242542703101233
11     11          11   2020-06-21 12:16:47         571465035400
12     12          12   2020-06-21 12:17:21     6593250708747804
13     13          13   2020-06-21 12:18:27        4988304376504
14     14          14   2020-06-21 12:18:37     6011504998544485
15     15          15   2020-06-21 12:18:41     4570636521433188
16     16          16   2020-06-21 12:18:54  4906628655840914250
17     17          17   2020-06-21 12:19:50     4908846471916297
18     18          18   2020-06-21 12:19:56  4861310130652566408
19     19          19   2020-06-21 12:20:13     6538441737335434

                                merchant        category     amt      first  \
0                  fraud_Kirlin and Sons   personal_care    2.86       Jeff
1                   fraud_Sporer-Keebler   personal_care   29.84     Joanne
2   fraud_Swaniawski, Nitzsche and Welch  health_fitness   41.28     Ashley
3                      fraud_Haley Group        misc_pos   60.05      Brian
4                  fraud_Johnston-Casper          travel    3.19     Nathan
5                    fraud_Daugherty LLC       kids_pets   19.55   Danielle
6                    fraud_Romaguera Ltd  health_fitness  133.93      Kayla
7                      fraud_Reichel LLC   personal_care   10.37      Paula
8      fraud_Goyette, Howell and Collier    shopping_pos    4.37      David
9                    fraud_Kilback Group     food_dining   66.54      Kayla
10          fraud_Feil, Hilpert and Koss     food_dining    7.01     Samuel
11                  fraud_Gottlieb Group       kids_pets   42.40      Louis
12                 fraud_Connelly-Carter            home    2.91    Melissa
13                fraud_Bechtelar-Rippin     food_dining    7.93    William
14                 fraud_Lubowitz-Walter       kids_pets    2.91     Ashley
15           fraud_Welch, Rath and Koepp   entertainment   24.73  Christine
16                    fraud_Hickle Group    shopping_pos    2.33    Charles
17         fraud_Lang, Towne and Schuppe       kids_pets   16.60     Lauren
18                  fraud_Morissette LLC   entertainment   80.11     Ashley
19                    fraud_Prosacco LLC   personal_care    5.71       Gina

        last gender  ...      lat      long city_pop  \
0    Elliott      M  ...  33.9659  -80.9355   333497
1   Williams      F  ...  40.3207 -110.4360      302
2      Lopez      F  ...  40.6729  -73.5365    34496
3   Williams      M  ...  28.5697  -80.8191    54767
4     Massey      M  ...  44.2529  -85.0170     1126
5      Evans      F  ...  42.1939  -76.7361      520
6     Sutton      F  ...  40.5070 -123.9743     1139
7    Estrada      F  ...  43.7557  -97.5936      343
8    Everett      M  ...  41.0001  -78.2357     3688
9     Obrien      F  ...  31.6591  -96.8094      263
10   Jenkins      M  ...  38.4921  -85.4524      564
11    Fisher      M  ...  43.0048 -108.8964     1645
12      Meza      F  ...  26.7383  -80.2760    26551
13  Thompson      M  ...  41.4575  -74.1659     2258
14   Whitney      F  ...  32.5104  -86.8138     1089
15   Leblanc      F  ...  28.8989  -81.2473    88735
16    Moreno      M  ...  24.6557  -81.3824    32891
17    Torres      F  ...  32.2779  -97.2351     5875
18      Cruz      F  ...  30.2385  -90.8435    10076
19    Grimes      F  ...  41.3851  -80.1752      606

                                      job         dob  \
0                     Mechanical engineer  1968-03-19
1                  Sales professional, IT  1990-01-17
2                       Librarian, public  1970-10-21
3                            Set designer  1987-07-25
4                      Furniture designer  1955-07-06
5                         Psychotherapist  1991-10-13
6                 Therapist, occupational  1951-01-15
7   Development worker, international aid  1972-03-05
8                           Advice worker  1973-05-27
9                               Barrister  1956-05-30
10                    Pensions consultant  1996-04-10
11                      Freight forwarder  1976-02-26
12                              Paramedic  1977-01-04
13                      Building surveyor  1937-03-17
14                     Materials engineer  1971-11-02
15              Commercial horticulturist  1988-04-09
16                           Town planner  1987-02-13
17              Radiographer, therapeutic  1992-07-24
18               Surveyor, rural practice  1977-12-16
19                         Energy manager  1997-09-22

                           trans_num   unix_time  merch_lat  merch_long  \
0   2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714
1   324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431
2   c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111
3   2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061
4   57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734
5   798db04aaceb4febd084f1a7c404da93  1371816937  41.747157  -77.584197
6   17003d7ce534440eadb10c4750e020e5  1371816944  41.499458 -124.888729
7   8be473af4f05fc6146ea55ace73e7ca2  1371816950  44.495498  -97.728453
8   71a1da150d1ce510193d7622e08e784e  1371816970  41.546067  -78.120238
9   a7915132c7c4240996ba03a47f81e3bd  1371816971  31.782919  -96.366185
10  3b8e4d02d9e1a3bf97cf449eb0317f2c  1371816980  38.977546  -84.727994
11  fa3071565d94fb286cb0ed398c6d61d3  1371817007  42.687774 -108.670054
12  a21cb82e7d8fdbf4062f15c9422a4ca6  1371817041  26.078460  -80.569932
13  d0d2b5cca5ae19e0a07dc7ef5d51e59e  1371817107  40.711680  -73.668384
14  61dca41a9728ea5fd6db99efd59768f8  1371817117  32.721131  -87.253846
15  ea11379e8aa1b08d584149d65770faee  1371817121  29.831550  -80.926829
16  00da72495351ce6bd9ecb75d51cca89b  1371817134  24.306325  -81.065169
17  67288141e8206f6f49706c1cef5b75d3  1371817190  33.182349  -97.919284
18  71bb6ee81f9af4d2a38bf6af2b614708  1371817196  30.449990  -89.930996
19  2d7640ea4f3bcd520a3c33200c393dd8  1371817213  40.508064  -79.615158

   is_fraud
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0

[20 rows x 24 columns]

In [3]:
import pandas as pd

df = pd.read_csv(df_path)

#Print the first 20 rows of the DataFrame
print(df.head(20))

    Unnamed: 0 trans_date_trans_time               cc_num  \
0            0   2020-06-21 12:14:25     2291163933867244
1            1   2020-06-21 12:14:33     3573030041201292
2            2   2020-06-21 12:14:53     3598215285024754
3            3   2020-06-21 12:15:15     3591919803438423
4            4   2020-06-21 12:15:17     3526826139003047
5            5   2020-06-21 12:15:37       30407675418785
6            6   2020-06-21 12:15:44      213180742685905
7            7   2020-06-21 12:15:50     3589289942931264
8            8   2020-06-21 12:16:10     3596357274378601
9            9   2020-06-21 12:16:11     3546897637165774
10          10   2020-06-21 12:16:20     2242542703101233
11          11   2020-06-21 12:16:47         571465035400
12          12   2020-06-21 12:17:21     6593250708747804
13          13   2020-06-21 12:18:27        4988304376504
14          14   2020-06-21 12:18:37     6011504998544485
15          15   2020-06-21 12:18:41     4570636521433188
16          16   2020-06-21 12:18:54  4906628655840914250
17          17   2020-06-21 12:19:50     4908846471916297
18          18   2020-06-21 12:19:56  4861310130652566408
19          19   2020-06-21 12:20:13     6538441737335434

                                merchant        category     amt      first  \
0                  fraud_Kirlin and Sons   personal_care    2.86       Jeff
1                   fraud_Sporer-Keebler   personal_care   29.84     Joanne
2   fraud_Swaniawski, Nitzsche and Welch  health_fitness   41.28     Ashley
3                      fraud_Haley Group        misc_pos   60.05      Brian
4                  fraud_Johnston-Casper          travel    3.19     Nathan
5                    fraud_Daugherty LLC       kids_pets   19.55   Danielle
6                    fraud_Romaguera Ltd  health_fitness  133.93      Kayla
7                      fraud_Reichel LLC   personal_care   10.37      Paula
8      fraud_Goyette, Howell and Collier    shopping_pos    4.37      David
9                    fraud_Kilback Group     food_dining   66.54      Kayla
10          fraud_Feil, Hilpert and Koss     food_dining    7.01     Samuel
11                  fraud_Gottlieb Group       kids_pets   42.40      Louis
12                 fraud_Connelly-Carter            home    2.91    Melissa
13                fraud_Bechtelar-Rippin     food_dining    7.93    William
14                 fraud_Lubowitz-Walter       kids_pets    2.91     Ashley
15           fraud_Welch, Rath and Koepp   entertainment   24.73  Christine
16                    fraud_Hickle Group    shopping_pos    2.33    Charles
17         fraud_Lang, Towne and Schuppe       kids_pets   16.60     Lauren
18                  fraud_Morissette LLC   entertainment   80.11     Ashley
19                    fraud_Prosacco LLC   personal_care    5.71       Gina

        last gender                         street  ...      lat      long  \
0    Elliott      M              351 Darlene Green  ...  33.9659  -80.9355
1   Williams      F               3638 Marsh Union  ...  40.3207 -110.4360
2      Lopez      F           9333 Valentine Point  ...  40.6729  -73.5365
3   Williams      M    32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191
4     Massey      M       5783 Evan Roads Apt. 465  ...  44.2529  -85.0170
5      Evans      F     76752 David Lodge Apt. 064  ...  42.1939  -76.7361
6     Sutton      F                010 Weaver Land  ...  40.5070 -123.9743
7    Estrada      F                350 Stacy Glens  ...  43.7557  -97.5936
8    Everett      M                4138 David Fall  ...  41.0001  -78.2357
9     Obrien      F     7921 Robert Port Suite 343  ...  31.6591  -96.8094
10   Jenkins      M  43235 Mckenzie Views Apt. 837  ...  38.4921  -85.4524
11    Fisher      M                45654 Hess Rest  ...  43.0048 -108.8964
12      Meza      F             244 Abbott Parkway  ...  26.7383  -80.2760
13  Thompson      M        977 Rita Grove Apt. 000  ...  41.4575  -74.1659
14   Whitney      F              4038 Smith Avenue  ...  32.5104  -86.8138
15   Leblanc      F      5097 Jodi Vista Suite 811  ...  28.8989  -81.2473
16    Moreno      M  838 Franklin Prairie Apt. 902  ...  24.6557  -81.3824
17    Torres      F              03030 White Lakes  ...  32.2779  -97.2351
18      Cruz      F   65417 Walsh Radial Suite 691  ...  30.2385  -90.8435
19    Grimes      F                444 Robert Mews  ...  41.3851  -80.1752

    city_pop                                    job         dob  \
0     333497                    Mechanical engineer  1968-03-19
1        302                 Sales professional, IT  1990-01-17
2      34496                      Librarian, public  1970-10-21
3      54767                           Set designer  1987-07-25
4       1126                     Furniture designer  1955-07-06
5        520                        Psychotherapist  1991-10-13
6       1139                Therapist, occupational  1951-01-15
7        343  Development worker, international aid  1972-03-05
8       3688                          Advice worker  1973-05-27
9        263                              Barrister  1956-05-30
10       564                    Pensions consultant  1996-04-10
11      1645                      Freight forwarder  1976-02-26
12     26551                              Paramedic  1977-01-04
13      2258                      Building surveyor  1937-03-17
14      1089                     Materials engineer  1971-11-02
15     88735              Commercial horticulturist  1988-04-09
16     32891                           Town planner  1987-02-13
17      5875              Radiographer, therapeutic  1992-07-24
18     10076               Surveyor, rural practice  1977-12-16
19       606                         Energy manager  1997-09-22

                           trans_num   unix_time  merch_lat  merch_long  \
0   2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714
1   324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431
2   c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111
3   2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061
4   57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734
5   798db04aaceb4febd084f1a7c404da93  1371816937  41.747157  -77.584197
6   17003d7ce534440eadb10c4750e020e5  1371816944  41.499458 -124.888729
7   8be473af4f05fc6146ea55ace73e7ca2  1371816950  44.495498  -97.728453
8   71a1da150d1ce510193d7622e08e784e  1371816970  41.546067  -78.120238
9   a7915132c7c4240996ba03a47f81e3bd  1371816971  31.782919  -96.366185
10  3b8e4d02d9e1a3bf97cf449eb0317f2c  1371816980  38.977546  -84.727994
11  fa3071565d94fb286cb0ed398c6d61d3  1371817007  42.687774 -108.670054
12  a21cb82e7d8fdbf4062f15c9422a4ca6  1371817041  26.078460  -80.569932
13  d0d2b5cca5ae19e0a07dc7ef5d51e59e  1371817107  40.711680  -73.668384
14  61dca41a9728ea5fd6db99efd59768f8  1371817117  32.721131  -87.253846
15  ea11379e8aa1b08d584149d65770faee  1371817121  29.831550  -80.926829
16  00da72495351ce6bd9ecb75d51cca89b  1371817134  24.306325  -81.065169
17  67288141e8206f6f49706c1cef5b75d3  1371817190  33.182349  -97.919284
18  71bb6ee81f9af4d2a38bf6af2b614708  1371817196  30.449990  -89.930996
19  2d7640ea4f3bcd520a3c33200c393dd8  1371817213  40.508064  -79.615158

    is_fraud
0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0

[20 rows x 23 columns]

In [5]:

#Create a SQLite database
conn = sqlite3.connect(db_path) 
cursor = conn.cursor()

#Run queries on the database
query = f"SELECT job, AVG(is_fraud) AS avg_fraud FROM {table_name} GROUP BY job ORDER BY avg_fraud DESC LIMIT 30;"  
#This pd function allows to execute a query and save outcome 
result = pd.read_sql_query(query, conn)
print(result)

# Close the connection
conn.close()

                                                  job  avg_fraud
0                                   Software engineer   1.000000
1                       Operational investment banker   1.000000
2                                     Engineer, water   1.000000
3                            Horticultural consultant   0.056338
4                     Accountant, chartered certified   0.055300
5                          Television camera operator   0.053571
6                       Designer, television/film set   0.048544
7                                        TEFL teacher   0.044053
8                                        Tour manager   0.041494
9                              Surveyor, hydrographic   0.039604
10                                     Hydrogeologist   0.039526
11                               Commissioning editor   0.035294
12                             Conservator, furniture   0.035176
13                        Nature conservation officer   0.034483
14                                Visual merchandiser   0.033898
15                     Investment banker, operational   0.031390
16                                      Buyer, retail   0.029412
17                        Engineer, building services   0.026846
18  Scientist, clinical (histocompatibility and im...   0.026634
19                      Advertising account executive   0.026562
20                      Scientist, research (medical)   0.025532
21                                          Ecologist   0.024887
22                        Civil Service fast streamer   0.024390
23                Engineer, broadcasting (operations)   0.023866
24                   Higher education careers adviser   0.023460
25                                        Optometrist   0.022222
26                               Licensed conveyancer   0.021970
27                       Research scientist (medical)   0.021786
28                     Teaching laboratory technician   0.021708
29                                  Psychiatric nurse   0.021605